Katherina kaplina homework 21
eugene-okulik/Katherina_K pull request #20
Opened 2024-07-14 18:59 UTC by KatherinaKaplina

2024-07-15 10:11 UTC, eugene-okulik requested changes
Структура хорошая. Но нужно сделать так, чтобы эти тесты могли запускаться на любом компе, на который скачают этот проект. И один метод унести в собственный класс.

2024-07-15 10:11 UTC, eugene-okulik commented on __init__.py
Этот файл не помещают в корень проекта. Добавлением этого файла сюда ты сказала, что это не корень проекта. Корень - та папка, которая на уровень выше. Но на уровень выше в репозитории уже нет папок.

2024-07-15 10:11 UTC, eugene-okulik commented on test_api_kkaplina/conftest.py
> +from project.Katherina_K.test_api_kkaplina.endpoints.create_object import CreateObject
Судя, по тому, как у тебя написаны импорты, в пайчарме у тебя открыт не проект, а какая-то папка, в которой много проектов. Открывать нужно именно тот проект, над которым работаешь. Иначе, рискуешь поломать все остальные проекты. И, судя по всему, в папке project у тебя тоже есть файл `__init__.py`, хотя эта папка к проекту не имеет отношения - это просто какая-то папка у тебя на компе. В итоге этот импорт сможет отработать только у тебя на компе потому что у меня на компе проект лежит не в папке project.

2024-07-15 10:11 UTC, eugene-okulik commented on test_api_kkaplina/conftest.py
> +    requests.delete(f'{url}/{object_id}')
Круто было бы и здесь воспользоваться теми методами, которые ты создала в классах.

2024-07-15 10:11 UTC, eugene-okulik commented on test_api_kkaplina/endpoints/partial_update_object.py
> +        return response.json()
Этот метод не относится к partial update object, он работает с другим ендпоинтом. Для него должен быть создан отдельный класс

2024-07-15 17:22 UTC, KatherinaKaplina commented on test_api_kkaplina/conftest.py
> +from project.Katherina_K.test_api_kkaplina.endpoints.create_object import CreateObject
я исправила:
 - сделала C:\Kate\lessons_AQA\project\Katherina_K\ как корневую папку, в папки ниже ее добавила __init__.py. 
 - но запускаю из Katherina_K\test_api_kkaplina>, если из \Katherina_K - ругается на модули из других папок ко мне не относящихся 
 
```
ImportError while loading conftest 'C:\Kate\lessons_AQA\project\Katherina_K\test_api_eokulik\conftest.py'.
test_api_eokulik\conftest.py:2: in <module>
    from endpoints.create_post import CreatePost
test_api_eokulik\endpoints\create_post.py:4: in <module>
    from test_api_eokuik.endpoints.endpoint import Endpoint
E   ModuleNotFoundError: No module named 'test_api_eokuik'
```

2024-07-16 08:11 UTC, eugene-okulik requested changes

2024-07-16 08:11 UTC, eugene-okulik commented on test_api_kkaplina/conftest.py
> +from test_api_kkaplina.endpoints.get_object import GetRequestObject
Файла get_object.py сейчас нет в репозитории

2024-07-16 08:11 UTC, eugene-okulik commented on test_api_kkaplina/conftest.py
> +from project.Katherina_K.test_api_kkaplina.endpoints.create_object import CreateObject
А как ты запускаешь? Я зашел в папку твоего это проекта с автотестами (перед этим кое-как добавил файл, который отсутствует) и запустил. Фейлд - этот тот, который пользуется отсутствующим файлом. Но на меня не ругалось о том, что каких-то модулей из других проектов не хватает.
![2024-07-16_11-06](https://github.com/user-attachments/assets/3f212fad-e06f-46b5-a82d-2428dc082684)

2024-07-16 08:53 UTC, KatherinaKaplina commented on test_api_kkaplina/conftest.py
> +from project.Katherina_K.test_api_kkaplina.endpoints.create_object import CreateObject
(venv) PS C:\Kate\lessons_AQA\project\Katherina_K\test_api_kkaplina> **pytest -vs**
=== test session starts=== 
C:\Kate\lessons_AQA\project\Katherina_K\venv\Scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Kate\lessons_AQA\project\Katherina_K\test_api_kkaplina
plugins: allure-pytest-2.13.5, xdist-3.6.1
collected 5 items                                                                                                                                                                                                                   

tests/test_1.py::test_add_object[data0] PASSED
tests/test_1.py::test_add_object[data1] PASSED
tests/test_1.py::test_update_object PASSED
tests/test_1.py::test_partially_update_object PASSED
tests/test_1.py::test_delete_object PASSED

2024-07-16 08:55 UTC, KatherinaKaplina commented on test_api_kkaplina/conftest.py
> +from test_api_kkaplina.endpoints.get_object import GetRequestObject
![image](https://github.com/user-attachments/assets/09b39db3-4605-428d-ac25-4b9007d79eb5)

2024-07-16 08:55 UTC, KatherinaKaplina commented on test_api_kkaplina/conftest.py
> +from test_api_kkaplina.endpoints.get_object import GetRequestObject
должен быть(

2024-07-16 08:59 UTC, KatherinaKaplina commented on test_api_kkaplina/conftest.py
> +from project.Katherina_K.test_api_kkaplina.endpoints.create_object import CreateObject
у меня теперь корень проекта Katherina_K, в нем __init__.py нет, далее во всех есть и они помечены как packages
![image](https://github.com/user-attachments/assets/4e6c0d80-ea8b-465c-abc7-1c3be1275ef7)

2024-07-16 09:02 UTC, KatherinaKaplina commented on test_api_kkaplina/conftest.py
> +from project.Katherina_K.test_api_kkaplina.endpoints.create_object import CreateObject
![2024-07-16_12h02_05](https://github.com/user-attachments/assets/643350dd-2a26-4dfc-a74d-c37cbe8fbdb1)
![2024-07-16_12h02_32](https://github.com/user-attachments/assets/8aa64673-64f5-4663-901d-5ab41c7f2652)

2024-07-16 10:23 UTC, eugene-okulik commented on test_api_kkaplina/conftest.py
> +from test_api_kkaplina.endpoints.get_object import GetRequestObject
Так он же вот прям красный. Ты значит ему даже git add не делала. Он никак не может попасть в коммит пока ему не сделали git add

2024-07-16 10:32 UTC, KatherinaKaplina commented on test_api_kkaplina/conftest.py
> +from test_api_kkaplina.endpoints.get_object import GetRequestObject
так а если я делала `git add .`  - ведь долдно было все попасть?

2024-07-16 14:33 UTC, eugene-okulik approved these changes

2024-07-16 14:33 UTC, eugene-okulik commented on test_api_kkaplina/conftest.py
> +from test_api_kkaplina.endpoints.get_object import GetRequestObject
Да, то для чего не сделан git add вообще отсутствует в репозитории.

2024-07-16 14:33 UTC, merged